# permissions for end users to edit projectsetups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectsetup-editor-role
rules:
- apiGroups:
  - webinar.consol.de
  resources:
  - projectsetups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webinar.consol.de
  resources:
  - projectsetups/status
  verbs:
  - get
