{{ if .Values.nodejs.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes the database server
  name: {{ include "nodejs.databaseServiceName" . }}
  labels:
    app.kubernetes.io/part-of: {{ .Values.nodejs.name }}
    application: {{ .Values.nodejs.name}}
spec:
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  selector:
    name: {{ include "nodejs.databaseServiceName" . }}
{{ end }}