{{ if .Values.java.enabled }}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    application: {{ .Values.java.name}}
    app.kubernetes.io/part-of: {{ .Values.java.name }}
  name: {{ .Values.java.name}}
  labels:
    app.openshift.io/runtime: java
    app.kubernetes.io/part-of: {{ .Values.java.name }}
spec:
  replicas: 1
  selector:
    deploymentConfig: {{ .Values.java.name}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: {{ .Values.java.name}}
        deploymentConfig: {{ .Values.java.name}}
      name: {{ .Values.java.name}}
    spec:
      containers:
      - env: []
        # image: ' '
        imagePullPolicy: Always
        name: {{ .Values.java.name}}
        ports:
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
      terminationGracePeriodSeconds: 75
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - {{ .Values.java.name}}
      from:
        kind: ImageStreamTag
        name: {{ .Values.java.name}}:latest
    type: ImageChange
  - type: ConfigChange
{{ end }}