{{ if .Values.rails.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rails.name }}
  labels:
    app.kubernetes.io/part-of: {{ .Values.rails.name }}
    application: {{ .Values.rails.name}}
stringData:
  application_password: {{ .Values.rails.application_password }}
  application_user: {{ .Values.rails.application_user }}
  {{ if .Values.rails.database.password }}
  database-password:  {{ .Values.rails.database.password }}
  {{ else }}
  database-password: {{ randAlphaNum 8 }}
  {{ end }}
  {{ if .Values.rails.database.user }}
  database-user:  {{ .Values.rails.database.user }}
  {{ else }}
  database-user: {{ randAlphaNum 8 }}
  {{ end }}
  {{ if .Values.rails.secret_key_base }}
  keybase:  {{ .Values.rails.secret_key_base }}
  {{ else }}
  keybase: {{ randAlphaNum 20 }}
  {{ end }}
{{ end }}