{{ if .Values.java.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The application's http port.
  labels:
    application: {{ .Values.java.name}}
    app.kubernetes.io/part-of: {{ .Values.java.name }}
  name: {{ .Values.java.name}}
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    deploymentConfig: {{ .Values.java.name}}
{{ end }}