{{ if .Values.java.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    description: Route for application's http service.
  labels:
    application: {{ .Values.java.name}}
    app.kubernetes.io/part-of: {{ .Values.java.name }}
  name: {{ .Values.java.name}}
spec:
  to:
    kind: Service
    name: {{ .Values.java.name}}
{{ end }}