---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: openshiftexamples.webinar.consol.de
spec:
  group: webinar.consol.de
  names:
    kind: OpenshiftExample
    listKind: OpenshiftExampleList
    plural: openshiftexamples
    singular: openshiftexample
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: OpenshiftExample is the Schema for the openshiftexamples API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of OpenshiftExample
            type: object
            required:
              - java
              - nodejs
              - rails
            properties:
              java:
                description: Sets up example java application
                type: object
                required:
                  - enabled
                properties:
                  name:
                    description: The name of the example java application
                    type: string
                    pattern: '^[a-z][a-z0-9\-]{5,25}$'
                  enabled:
                    description: If enabled the java example will be installed. 
                    type: boolean
              nodejs:
                description: Sets up example nodejs application
                type: object
                properties:
                  name:
                    description: The name of the example nodejs application
                    type: string
                    pattern: '^[a-z][a-z0-9\-]{5,25}$'
                  enabled:
                    description: If enabled the nodejs example will be installed. 
                    type: boolean
              rails:
                description: Sets up example rails application
                type: object
                properties:
                  name:
                    description: The name of the example rails application
                    type: string
                    pattern: '^[a-z][a-z0-9\-]{5,25}$'
                  enabled:
                    description: If enabled the rails example will be installed. 
                    type: boolean
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of OpenshiftExample
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
