apiVersion: webinar.consol.de/v1alpha1
kind: ProjectSetup
metadata:
  name: projectsetup-sample
spec:
  # Default values copied from <project_dir>/helm-charts/project-setup/values.yaml
  limit:
    default:
      cpu: 200m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    max:
      cpu: "5"
      memory: 4Gi
    maxLimitRequestRatio:
      cpu: "10"
      memory: "5"
    min:
      cpu: 50m
      memory: 128Mi
  quota:
    cpu: "1"
    memory: 1Gi
    storage: 1Gi
  rbac:
    user:
      admin:
      - olaf
      - superduperadmin
  
  
