apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Red Hat OpenJDK
    openshift.io/provider-display-name: Red Hat, Inc.
    samples.operator.openshift.io/version: 4.7.19
    version: 1.4.17
  labels:
    samples.operator.openshift.io/managed: "true"
    xpaas: 1.4.17
  name: java
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and run Java applications using Maven and OpenJDK 11.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 11
      sampleContextDir: undertow-servlet
      sampleRepo: https://github.com/jboss-openshift/openshift-quickstarts
      supports: java:11,java
      tags: builder,java,openjdk,hidden
      version: "11"
    from:
      kind: DockerImage
      name: registry.redhat.io/openjdk/openjdk-11-rhel7:latest
    generation: 2
    name: "11"
    referencePolicy:
      type: Local
  - annotations:
      description: Build and run Java applications using Maven and OpenJDK 8.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 8
      sampleContextDir: undertow-servlet
      sampleRepo: https://github.com/jboss-openshift/openshift-quickstarts
      supports: java:8,java
      tags: builder,java,openjdk,hidden
      version: "8"
    from:
      kind: DockerImage
      name: registry.redhat.io/redhat-openjdk-18/openjdk18-openshift:latest
    generation: 2
    name: "8"
    referencePolicy:
      type: Local
  - annotations:
      description: Build and run Java applications using Maven.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Java (Latest)
      sampleContextDir: undertow-servlet
      sampleRepo: https://github.com/jboss-openshift/openshift-quickstarts
      supports: java
      tags: builder,java,openjdk
      version: latest
    from:
      kind: ImageStreamTag
      name: openjdk-11-ubi8
    generation: 1
    name: latest
    referencePolicy:
      type: Local
  - annotations:
      description: Build and run Java applications using Maven and OpenJDK 11.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 11 (RHEL 7)
      sampleContextDir: undertow-servlet
      sampleRepo: https://github.com/jboss-openshift/openshift-quickstarts
      supports: java:11,java
      tags: builder,java,openjdk
      version: "11"
    from:
      kind: DockerImage
      name: registry.redhat.io/openjdk/openjdk-11-rhel7:latest
    generation: 2
    name: openjdk-11-el7
    referencePolicy:
      type: Local
  - annotations:
      description: Build and run Java applications using Maven and OpenJDK 11.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 11 (UBI 8)
      sampleContextDir: undertow-servlet
      sampleRepo: https://github.com/jboss-openshift/openshift-quickstarts
      supports: java:11,java
      tags: builder,java,openjdk
      version: "11"
    from:
      kind: DockerImage
      name: registry.redhat.io/ubi8/openjdk-11:latest
    generation: 2
    name: openjdk-11-ubi8
    referencePolicy:
      type: Local
  - annotations:
      description: Build and run Java applications using Maven and OpenJDK 8.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 8 (RHEL 7)
      sampleContextDir: undertow-servlet
      sampleRepo: https://github.com/jboss-openshift/openshift-quickstarts
      supports: java:8,java
      tags: builder,java,openjdk
      version: "8"
    from:
      kind: DockerImage
      name: registry.redhat.io/redhat-openjdk-18/openjdk18-openshift:latest
    generation: 2
    name: openjdk-8-el7
    referencePolicy:
      type: Local
  - annotations:
      description: Build and run Java applications using Maven and OpenJDK 8.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 8 (UBI 8)
      sampleContextDir: undertow-servlet
      sampleRepo: https://github.com/jboss-openshift/openshift-quickstarts
      supports: java:8,java
      tags: builder,java,openjdk
      version: "8"
    from:
      kind: DockerImage
      name: registry.redhat.io/ubi8/openjdk-8:latest
    generation: 2
    name: openjdk-8-ubi8
    referencePolicy:
      type: Local
