apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Node.js
  labels:
    samples.operator.openshift.io/managed: "true"
  name: nodejs
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and run Node.js 10 applications on RHEL 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-nodejs-container/blob/master/10/README.md.
      iconClass: icon-nodejs
      openshift.io/display-name: Node.js 10
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/nodejs-ex.git
      tags: builder,nodejs,hidden
      version: "10"
    from:
      kind: DockerImage
      name: registry.redhat.io/rhscl/nodejs-10-rhel7:latest
    generation: 2
    name: "10"
    referencePolicy:
      type: Local
  - annotations:
      description: Build and run Node.js 10 applications on UBI 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-nodejs-container/blob/master/10/README.md.
      iconClass: icon-nodejs
      openshift.io/display-name: Node.js 10 (UBI 7)
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/nodejs-ex.git
      tags: builder,nodejs
      version: "10"
    from:
      kind: DockerImage
      name: registry.redhat.io/ubi7/nodejs-10:latest
    generation: 2
    name: 10-ubi7
    referencePolicy:
      type: Local
  - annotations:
      description: Build and run Node.js 10 applications on UBI 8. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-nodejs-container/blob/master/10/README.md.
      iconClass: icon-nodejs
      openshift.io/display-name: Node.js 10 (UBI 8)
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/nodejs-ex.git
      tags: builder,nodejs
      version: "10"
    from:
      kind: DockerImage
      name: registry.redhat.io/ubi8/nodejs-10:latest
    generation: 2
    name: 10-ubi8
    referencePolicy:
      type: Local
  - annotations:
      description: Build and run Node.js 12 applications on RHEL 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-nodejs-container/blob/master/12/README.md.
      iconClass: icon-nodejs
      openshift.io/display-name: Node.js 12
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/nodejs-ex.git
      tags: builder,nodejs,hidden
      version: "12"
    from:
      kind: DockerImage
      name: registry.redhat.io/rhscl/nodejs-12-rhel7:latest
    generation: 2
    name: "12"
    referencePolicy:
      type: Local
  - annotations:
      description: Build and run Node.js 12 applications on UBI 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-nodejs-container/blob/master/12/README.md.
      iconClass: icon-nodejs
      openshift.io/display-name: Node.js 12 (UBI 7)
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/nodejs-ex.git
      tags: builder,nodejs
      version: "12"
    from:
      kind: DockerImage
      name: registry.redhat.io/ubi7/nodejs-12:latest
    generation: 2
    name: 12-ubi7
    referencePolicy:
      type: Local
  - annotations:
      description: Build and run Node.js 12 applications on UBI 8. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-nodejs-container/blob/master/12/README.md.
      iconClass: icon-nodejs
      openshift.io/display-name: Node.js 12 (UBI 8)
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/nodejs-ex.git
      tags: builder,nodejs
      version: "12"
    from:
      kind: DockerImage
      name: registry.redhat.io/ubi8/nodejs-12:latest
    generation: 2
    name: 12-ubi8
    referencePolicy:
      type: Local
  - annotations:
      description: Build and run Node.js 14 applications on UBI 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-nodejs-container/blob/master/14/README.md.
      iconClass: icon-nodejs
      openshift.io/display-name: Node.js 14 (UBI 7)
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/nodejs-ex.git
      tags: builder,nodejs
      version: "14"
    from:
      kind: DockerImage
      name: registry.redhat.io/ubi7/nodejs-14:latest
    generation: 2
    name: 14-ubi7
    referencePolicy:
      type: Local
  - annotations:
      description: Build and run Node.js 14 applications on UBI 8. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-nodejs-container/blob/master/14/README.md.
      iconClass: icon-nodejs
      openshift.io/display-name: Node.js 14 (UBI 8)
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/nodejs-ex.git
      tags: builder,nodejs
      version: "14"
    from:
      kind: DockerImage
      name: registry.redhat.io/ubi8/nodejs-14:latest
    generation: 2
    name: 14-ubi8
    referencePolicy:
      type: Local
  - annotations:
      description: |-
        Build and run Node.js applications on UBI. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-nodejs-container/blob/master/14/README.md.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of Node.js available on OpenShift, including major version updates.
      iconClass: icon-nodejs
      openshift.io/display-name: Node.js (Latest)
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/nodejs-ex.git
      supports: nodejs
      tags: builder,nodejs
    from:
      kind: ImageStreamTag
      name: 14-ubi8
    generation: 1
    name: latest
    referencePolicy:
      type: Local
