# permissions for end users to view openshiftexamples.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshiftexample-viewer-role
rules:
- apiGroups:
  - webinar.consol.de
  resources:
  - openshiftexamples
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webinar.consol.de
  resources:
  - openshiftexamples/status
  verbs:
  - get
