apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: create-project
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: gitops
    repoURL: git@github.com:olaf-meyer/helm-webinar.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: webinar.consol.de
      kind: OpenshiftExample
      jsonPointers:
        - /spec/java
        - /spec/nodejs
        - /spec/rails
