---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projectsetups.webinar.consol.de
spec:
  group: webinar.consol.de
  names:
    kind: ProjectSetup
    listKind: ProjectSetupList
    plural: projectsetups
    singular: projectsetup
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ProjectSetup is the Schema for the projectsetups API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of ProjectSetup
            type: object
            required:
              - rbac
            properties:
              quota:
                description: Defines configuration for project quota
                type: object
                properties:
                  cpu:
                    description: The overall requested maximum cpu value.
                    type: string
                    pattern: '^(\d+m|\d+(\.\d{1,3})?)$'
                  memory:
                    description: The overall requested maximum memory value.
                    type: string
                    pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
                  storage:
                    description: The overall maximum requested storage.
                    type: string
                    pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
              limit:
                description: Usage limits for each kind of resource.
                type: object
                properties:
                  default:
                    description: Default resource requirement limit value by resource name if resource limit is omitted.
                    type: object
                    properties:
                      cpu:
                        type: string
                        pattern: '^(\d+m|\d+(\.\d{1,3})?)$'
                      memory:
                        type: string
                        pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
                  defaultRequest:
                    description: DefaultRequest is the default resource requirement request value by resource name if resource request is omitted.
                    type: object
                    properties:
                      cpu:
                        type: string
                        pattern: '^(\d+m|\d+(\.\d{1,3})?)$'
                      memory:
                        type: string
                        pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
                  maxLimitRequestRatio:
                    description: MaxLimitRequestRatio if specified, the named resource must have a request and limit that are both non-zero where limit divided by request is less than or equal to the enumerated value; this represents the max burst for the named resource.
                    type: object
                    properties:
                      cpu:
                        type: string
                        pattern: '^(\d+m|\d+(\.\d{1,3})?)$'
                      memory:
                        type: string
                        pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
                  min:
                    description: Min usage constraints on this kind by resource name.
                    type: object
                    properties:
                      cpu:
                        type: string
                        pattern: '^(\d+m|\d+(\.\d{1,3})?)$'
                      memory:
                        type: string
                        pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
                  max:
                    description: Max usage constraints on this kind by resource name.
                    type: object
                    properties:
                      cpu:
                        type: string
                        pattern: '^(\d+m|\d+(\.\d{1,3})?)$'
                      memory:
                        type: string
                        pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
              rbac:
                description: Permission setting for the new namespace
                type: object
                properties:
                  user:
                    description: Permission settings for users
                    type: object
                    properties:
                      admin:
                        description: A list with names of the namespace admins
                        type: array
                        items:
                          type: string
          status:
            description: Status defines the observed state of ProjectSetup
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
